#include:
#  - remote: "https://raw.githubusercontent.com/rabbids-incubator/gitlab-pipeline-definitions/feature/dotnet-templates/dotnet/ci.yml"

image: mcr.microsoft.com/dotnet/sdk:6.0

variables:
  ROOT_FOLDER: .
  BUILD_SOURCEBRANCHNAME: $CI_COMMIT_BRANCH
  BUILD_BUILDID: $CI_PIPELINE_ID
  MSSQL_HOST: localmssql
  ACCEPT_EULA: "Y"
  SA_PASSWORD: s0m3Str0ng!P@ssw0rd

stages:
  - build
  - pack
  - test

services:
  - docker:dind
  # see: https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker
  - name: mcr.microsoft.com/mssql/server:2019-latest
    alias: mssql

docker_build:
  stage: build
  image: docker:latest
  script:
    - docker build -t example-image:latest .

# avoid duplicate runs
# CI_PIPELINE_SOURCE=push|external_pull_request_event|schedule
workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "external_pull_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

#.dotnet_build:
build:
  stage: build
  script:
    - env
    - cd $ROOT_FOLDER
    - dotnet restore
    - dotnet build --no-restore --configuration Debug

db-init:
  stage: build
  image: docker:latest
  script:
    # initializes local SQL Server database for integrations tests
    - docker ps
    - docker cp $PWD/scripts/mssql/db-init.sql mssql:/home/db-init.sql
    - docker exec mssql ls "/home"
    - docker exec mssql /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD -i /home/db-init.sql

#.dotnet_test_sonar:
test:
  stage: test
  variables:
    ServiceNow__RestApi__BaseUrl: $SERVICENOW_SANDBOX_URL
    ServiceNow__RestApi__Username: $SERVICENOW_SANDBOX_USERNAME
    ServiceNow__RestApi__Password: $SERVICENOW_SANDBOX_USERPWD
    COBERTURA_REPORT_FILEPATH: ./test/*/TestResults/*/coverage.cobertura.xml
    REPORTGENERATOR_OPTIONS: -targetdir:sonarqubecoverage -reporttypes:SonarQube
    SONAR_EXTRA_PARAMETERS: /d:sonar.cpd.exclusions=**/*Generated*.cs /d:sonar.coverageReportPaths=./sonarqubecoverage/SonarQube.xml
    ServiceNow__SqlServer__DataSource: localmssql
    ServiceNow__SqlServer__UserId: SA
    ServiceNow__SqlServer__Password: s0m3Str0ng!P@ssw0rd
    ServiceNow__SqlServer__InitialCatalog: TestDB
  script:
    # installs sonar tools
    - apt update
    - apt install -y default-jre
    - dotnet tool install --global dotnet-sonarscanner
    - dotnet tool install --global dotnet-reportgenerator-globaltool
    - export PATH="$PATH:/root/.dotnet/tools"
    - cd $ROOT_FOLDER
    # runs all tests with sonar analysis
    - dotnet restore
    - dotnet sonarscanner begin /o:$SONAR_ORGANIZATION /k:$SONAR_PROJECTKEY /d:sonar.host.url=$SONAR_HOSTURL $SONAR_EXTRA_PARAMETERS
    - dotnet test --configuration Debug --logger:"junit;LogFilePath=..\..\artifacts\{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose" --collect:"XPlat Code Coverage"
    - reportgenerator "-reports:$COBERTURA_REPORT_FILEPATH" $REPORTGENERATOR_OPTIONS
    - dotnet sonarscanner end
  #dependencies:
  #  - build
  artifacts:
    when: always
    paths:
      - ./**/*test-result.xml
      - $COBERTURA_REPORT_FILEPATH
    reports:
      junit:
        - ./**/*test-result.xml
      cobertura: $COBERTURA_REPORT_FILEPATH
  only:
    - external_pull_requests
    - main

# ref. https://docs.microsoft.com/en-us/nuget/nuget-org/publish-a-package
#.dotnet_pack:
pack:
  stage: build
  script:
    - cd $ROOT_FOLDER
    - dotnet restore
    - dotnet build --no-restore --configuration Release
    - dotnet pack --no-build --configuration Release -o output
    - ls -alrt output
    - for f in output/*.nupkg; do dotnet nuget push "$f" --api-key $NUGET_APIKEY --source https://api.nuget.org/v3/index.json ; done
  only:
    refs:
      - main
    changes:
      - Directory.Build.props
    variables:
      - $CI_PIPELINE_SOURCE == "push"

#build:
#  extends: .dotnet_build

#pack:
#  extends: .dotnet_pack

#test:
#  extends: .dotnet_test
