include:
  - remote: "https://raw.githubusercontent.com/rabbids-incubator/gitlab-pipeline-definitions/feature/dotnet-templates/dotnet/ci.yml"

build:
  extends: .dotnet_build

test:
  extends: .dotnet_test
